import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Under normal circumstances, this file is generated by `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfz73AvIAC73dzj5Rszb7g_NOk3W61wE',
    appId: '1:353094117552:web:ee5a6ed47b7bf5f243f375',
    messagingSenderId: '353094117552',
    projectId: 'fixwaala',
    authDomain: 'fixwaala.firebaseapp.com',
    storageBucket: 'fixwaala.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwqEp9k5eiMV6alq4vI9IZZjN7hq09hBA',
    appId: '1:353094117552:android:68566ce04ae08b5143f375',
    messagingSenderId: '353094117552',
    projectId: 'fixwaala',
    storageBucket: 'fixwaala.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-apiKey',
    appId: 'placeholder-appId',
    messagingSenderId: 'placeholder-messagingSenderId',
    projectId: 'placeholder-projectId',
    storageBucket: 'placeholder-storageBucket',
    iosBundleId: 'placeholder-iosBundleId',
  );
}
